### ISSUE TITLE
Failed to load plugin (error message)

### ISSUE THREAD

**Issue by albertoloscerritos** [mdelobelle/obsidian_supercharged_links#191]
I get the following error message when i launch obsidian, but everything seems to be working fine.

![failed](https://github.com/mdelobelle/obsidian_supercharged_links/assets/16707033/2ba45f93-850f-49ca-9bfe-a5bcdbb64816)

I'm running obsidian 1.4.3
Hope it helps.
Let me know if you need more info

**Comment by accept82** [comment]
I support, Obsidian gives an error when starting

**Comment by merlinuwe** [comment]
The same on my device. 

SYSTEM INFO:
	Obsidian version: v1.4.5
	Installer version: v1.4.5
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 65
	Restricted mode: off
	Plugins installed: 104
	Plugins enabled: 65
		1: Vault Statistics v0.1.3
		2: Unicode Search v0.4.1
		3: Typing Transformer v0.4.0
		4: Text Extractor v0.4.6
		5: Templater v1.16.0
		6: Tasks v4.6.1
		7: Tag & Word Cloud v1.3.2
		8: Symbols Prettifier v1.1.1
		9: Style Settings v1.0.7
		10: Show Current File Path v0.5.2
		11: Recent Files v1.3.8
		12: Reading View Enhancer v0.1.4
		13: Quiet Outline v0.3.15
		14: Quick Explorer v0.2.8
		15: Plotly v0.0.6
		16: Paste image rename v1.6.1
		17: Omnisearch v1.16.0
		18: Obsidian Link Converter v0.1.5
		19: Obsidian Enhancing Export v1.8.7
		20: Obsidian Camera v1.5.0
		21: Number Headings v1.13.0
		22: Minimal Theme Settings v7.2.2
		23: Mathpad v0.8.14
		24: Linter v1.20.0
		25: Link Archive v0.2.0
		26: Kroki v1.2.3
		27: Image Layouts v0.10.0
		28: Icon Folder v2.1.2
		29: Hover Editor v0.11.14
		30: Homepage v3.5.2
		31: Fullscreen mode plugin v0.1.2
		32: File Explorer Note Count v1.2.1
		33: Export Image plugin v1.0.3
		34: Execute Code v1.8.1
		35: Excel to Markdown Table v0.4.0
		36: Editor Syntax Highlight v0.1.3
		37: Editing Toolbar v2.3.1
		38: Dictionary v2.22.0
		39: Desmos v0.6.6
		40: Dataview v0.5.56
		41: Custom Classes v2.6.1
		42: Creases v0.7.0
		43: Copy document as HTML v0.5.0
		44: Completr v3.2.0
		45: Commander v0.5.0
		46: Colorful Note Borders v0.2.4
		47: Chronology v1.1.7
		48: Chem v0.2.1
		49: Charts View v1.2.5
		50: Buttons v0.4.19
		51: Auto Glossary v0.9.0
		52: Auto Class v2.3.0
		53: Audio Player v0.1.1
		54: Advanced URI v1.38.1
		55: Admonition v10.0.1
		56: Android nomedia v0.1.0
		57: Advanced Tables v0.19.1
		58: Codeblock Customizer v1.2.1
		59: Vault Changelog v0.1.0
		60: Sidebar Expand on Hover v1.0.1
		61: Natural Language Dates v0.6.1
		62: Sortable v0.3.1
		63: Todo sort v1.0.0
		64: Solve v0.3.3
		65: Supercharged Links v0.10.0

**Comment by merlinuwe** [comment]
Thank you very much for solving. ;-)

**Comment by accept82** [comment]
Thank you for the update, the bug is fixed, everything worked fine!

**Comment by mkasu** [comment]
Hmm I can confirm it's fixed on Desktop but I still see this error on mobile (v1.4.8 on iPhone).

**Comment by leelhn2345** [comment]
whenever i close a file, these error messages appear in the developer's console

![image](https://github.com/mdelobelle/obsidian_supercharged_links/assets/64735315/710f84eb-e270-4790-aab2-64b1e14855ac)

**Comment by tkern** [comment]
Also getting the error still with 0.10.2

**Comment by HEmile** [comment]
@mkasu I don't think there's an Obsidian version on mobile that supports properties yet, which causes a conflict... This version of supercharged links was developed for 0.10.x. 

@leelhn2345 Good catch. Should be fixed with https://github.com/mdelobelle/obsidian_supercharged_links/commit/db02a5d049116e45a53b5b6395bd1959265e8d86
