### ISSUE TITLE
support new bases tables?

### ISSUE THREAD

**Issue by zeltak** [mdelobelle/obsidian_supercharged_links#245]
Hi

i was wondering if supercharged links could support the new obsidian bases. 

ie the current table links dont seem to get picked up by supercharged links

![Image](https://github.com/user-attachments/assets/d9b7584f-9dec-4f19-a0de-f79eae6f5e7a)

where as in dataview, the file explorer etc they do show up with correct colors

![Image](https://github.com/user-attachments/assets/22f1c504-6547-438f-9435-95ef83341527)

thx so much for condiering!

Z

**Comment by HEmile** [comment]
Hi, thanks for the suggestion (this seems to be a popular request, haha!)

This should work now. I haven't tested the performance on low-end pcs though. Please submit an issue if the performance is poor.

<img width="1171" height="802" alt="Image" src="https://github.com/user-attachments/assets/a24efc7a-56fc-4254-875f-f687b4cd82e6" />

**Comment by flowing-abyss** [comment]
Thanks a lot for the fix! One thing though — embedded bases (`![[table.base]]`) still don’t get the Supercharged highlighting.

**Comment by zeltak** [comment]
works great thx so much!!

**Comment by HEmile** [comment]
@flowing-abyss that's fixed in #251 :)
