### ISSUE TITLE
Bug: Markdown links do not work in live preview

### ISSUE THREAD

**Issue by javiavid** [mdelobelle/obsidian_supercharged_links#80]
I don't see the icons when I have a markdown link in live preview, in reading mode it works fine.

**Comment by HEmile** [comment]
What is your CSS? And do you mean with "Markdown link" a link of the form [alias](note name)?

**Comment by javiavid** [comment]
My CSS is:
```
.data-link-icon[data-link-category$="People" i]::before{
    content: "👤 "
}
```

And this is the result:

![image](https://user-images.githubusercontent.com/7627504/151759891-cea98e57-8d89-48f9-876a-a9ce347332bf.png)


Thanks

**Comment by HEmile** [comment]
I see, so the issue is the markdown links.

**Comment by avirosso** [comment]
When will this bug be fixed? 

Obsidian is a markdown editor so it should work with standard markdown links in Live Preview too.

Thanks in advance!

**Comment by HEmile** [comment]
Right, I'll look into this one soon.

**Comment by HEmile** [comment]
Should work now. Let me know if there are issues!

**Comment by avirosso** [comment]
Thanks for the quick fix & reply - unfortunately it still doesn't work with standard markdown links in Live Preview ...

(It works fine in Reading Mode, File Browser and Plugins eg backlinks panel and with wikilinks)

Supercharged Links Version: 0.6.7
Obsidian Version: 0.13.33 (Installer: 0.13.31)
(Scheme: tested with standard theme and minimal theme)

Any idea?

**Comment by HEmile** [comment]
Hmm... Have you refreshed Obsidian to be sure? I just tried again and it's certainly working for me from my tests:
Source mode:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/1289165/160232538-413701a5-ea0a-4629-bda1-0bbcdbc2d69a.png">

Live preview: 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1289165/160232554-f10e7d56-21d5-48aa-a21f-a6ab6ff78f99.png">

**Comment by avirosso** [comment]
Thanks for investigtion!

Maybe it works for your example, because there are no 'complete internal markdown urls' (no path, no '.md')

See my examples (Source mode and Live Preview):

![Source Mode](https://user-images.githubusercontent.com/95497044/160233294-4018066d-a60c-4516-af13-3234564fa7ee.png)

![Live Preview](https://user-images.githubusercontent.com/95497044/160233298-4b5ee571-5397-417c-b459-23288c5a7bce.png)

**Comment by HEmile** [comment]
Ahhh, right. Yeah that must be it. I'll continue investigating that!

**Comment by HEmile** [comment]
Edit mode
<img width="757" alt="image" src="https://user-images.githubusercontent.com/1289165/160235412-adf890d5-b4a1-43ee-ab0c-acf5bc8f6a60.png">

Live preview
<img width="533" alt="image" src="https://user-images.githubusercontent.com/1289165/160235423-8581c7aa-8aa7-44a9-947f-68f09944f4fb.png">

Looks like this works!

**Comment by avirosso** [comment]
Thanks! - although it works for (Options > Files & Links > New link format): "Absolute path in Vault", ist does NOT for "Relative Path to file" and "Shortest Path when possible" .... (sorry for the trouble on weekend)

**Comment by HEmile** [comment]
Haha... so many possibilities to account for! Okay... I'll look at that later

**Comment by avirosso** [comment]
I think this issue should be 'reopened' (so that it is not forgotten)?

**Comment by avirosso** [comment]
Hi, 

is there any chance this bug will be fixed in the near future?

Reminder: It works already for 'absolute path, so I guess it shouldn't be a big issue to fix it for 'relative path' and shortest path' too ...?

Thanks in advance!
